apiVersion: apps/v1
kind: Deployment
metadata:
  name: xlaodie
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xlaodie
  template:
    metadata:
      labels:
        app: xlaodie
    spec:
      containers:
      - image: okteto.dev/ray:latest
        name: xlaodie
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "0adb48a6-a846-4782-b8f9-9e7f023c9594"
        - name: Vless_Path
          value: "/vlpoog"
        - name: Vmess_UUID
          value: "0adb48a6-a846-4782-b8f9-9e7f023c9594"
        - name: Vmess_Path
          value: "/vmokpp"
        - name: Share_Path
          value: "/v2link"
