apiVersion: v1
kind: Service
metadata:
  name: lapokok1
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "lapokok1"
    port: 8080
  selector:
    app: lapokok1
